databases:
  - name: my-budget
    databaseName: my_budget_0lev_1ut3_r5du
    user: my_budget_0lev_user

services:
  - type: web
    name: budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_budget_0lev_1ut3_r5du
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false